// Code generated by "stringer -type=ClientMessageType"; DO NOT EDIT.

package rfb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SetPixelFormat-0]
	_ = x[SetEncodings-2]
	_ = x[FramebufferUpdateRequest-3]
	_ = x[KeyEvent-4]
	_ = x[PointerEvent-5]
	_ = x[ClientCutText-6]
	_ = x[ClientFence-248]
	_ = x[QEMUExtendedKeyEvent-255]
}

const (
	_ClientMessageType_name_0 = "SetPixelFormat"
	_ClientMessageType_name_1 = "SetEncodingsFramebufferUpdateRequestKeyEventPointerEventClientCutText"
	_ClientMessageType_name_2 = "ClientFence"
	_ClientMessageType_name_3 = "QEMUExtendedKeyEvent"
)

var (
	_ClientMessageType_index_1 = [...]uint8{0, 12, 36, 44, 56, 69}
)

func (i ClientMessageType) String() string {
	switch {
	case i == 0:
		return _ClientMessageType_name_0
	case 2 <= i && i <= 6:
		i -= 2
		return _ClientMessageType_name_1[_ClientMessageType_index_1[i]:_ClientMessageType_index_1[i+1]]
	case i == 248:
		return _ClientMessageType_name_2
	case i == 255:
		return _ClientMessageType_name_3
	default:
		return "ClientMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
