// Code generated by "stringer -type=SecuritySubType"; DO NOT EDIT.

package rfb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SecSubTypeUnknown-0]
	_ = x[SecSubTypeVeNCrypt01Unknown-0]
	_ = x[SecSubTypeVeNCrypt01Plain-19]
	_ = x[SecSubTypeVeNCrypt01TLSNone-20]
	_ = x[SecSubTypeVeNCrypt01TLSVNC-21]
	_ = x[SecSubTypeVeNCrypt01TLSPlain-22]
	_ = x[SecSubTypeVeNCrypt01X509None-23]
	_ = x[SecSubTypeVeNCrypt01X509VNC-24]
	_ = x[SecSubTypeVeNCrypt01X509Plain-25]
	_ = x[SecSubTypeVeNCrypt02Unknown-0]
	_ = x[SecSubTypeVeNCrypt02Plain-256]
	_ = x[SecSubTypeVeNCrypt02TLSNone-257]
	_ = x[SecSubTypeVeNCrypt02TLSVNC-258]
	_ = x[SecSubTypeVeNCrypt02TLSPlain-259]
	_ = x[SecSubTypeVeNCrypt02X509None-260]
	_ = x[SecSubTypeVeNCrypt02X509VNC-261]
	_ = x[SecSubTypeVeNCrypt02X509Plain-262]
}

const (
	_SecuritySubType_name_0 = "SecSubTypeUnknown"
	_SecuritySubType_name_1 = "SecSubTypeVeNCrypt01PlainSecSubTypeVeNCrypt01TLSNoneSecSubTypeVeNCrypt01TLSVNCSecSubTypeVeNCrypt01TLSPlainSecSubTypeVeNCrypt01X509NoneSecSubTypeVeNCrypt01X509VNCSecSubTypeVeNCrypt01X509Plain"
	_SecuritySubType_name_2 = "SecSubTypeVeNCrypt02PlainSecSubTypeVeNCrypt02TLSNoneSecSubTypeVeNCrypt02TLSVNCSecSubTypeVeNCrypt02TLSPlainSecSubTypeVeNCrypt02X509NoneSecSubTypeVeNCrypt02X509VNCSecSubTypeVeNCrypt02X509Plain"
)

var (
	_SecuritySubType_index_1 = [...]uint8{0, 25, 52, 78, 106, 134, 161, 190}
	_SecuritySubType_index_2 = [...]uint8{0, 25, 52, 78, 106, 134, 161, 190}
)

func (i SecuritySubType) String() string {
	switch {
	case i == 0:
		return _SecuritySubType_name_0
	case 19 <= i && i <= 25:
		i -= 19
		return _SecuritySubType_name_1[_SecuritySubType_index_1[i]:_SecuritySubType_index_1[i+1]]
	case 256 <= i && i <= 262:
		i -= 256
		return _SecuritySubType_name_2[_SecuritySubType_index_2[i]:_SecuritySubType_index_2[i+1]]
	default:
		return "SecuritySubType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
