// Code generated by "stringer -type=SessionType"; DO NOT EDIT.

package rfb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientSessionType-0]
	_ = x[ServerSessionType-1]
	_ = x[RecorderSessionType-2]
	_ = x[PlayerSessionType-3]
	_ = x[CanvasSessionType-4]
}

const _SessionType_name = "ClientSessionTypeServerSessionTypeRecorderSessionTypePlayerSessionTypeCanvasSessionType"

var _SessionType_index = [...]uint8{0, 17, 34, 53, 70, 87}

func (i SessionType) String() string {
	if i >= SessionType(len(_SessionType_index)-1) {
		return "SessionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionType_name[_SessionType_index[i]:_SessionType_index[i+1]]
}
